### PR TITLE
Using `const` wherever it is possible

### PR DESCRIPTION
**Pull request by glauco**
ES6 allows you to create variables with block scope instead of
function scope using the let and const keywords.
This might help avoiding silly programming mistakes in the future.

### CODE REVIEW

**Comment by iefserge** [comment]
@glauco Thank you for the PR, it looks great! 
However, using `let` and `const` instead of `var` reduces performance in v8. Server benchmark I'm using is `node benchmark/server-benchmark.js`, getting almost 3X difference.

```
node v6.1.0

let/const (this branch)
done 100000 connections in 4144ms (0.0414ms per connection)

var (master branch)
done 100000 connections in 1389ms (0.0139ms per connection)
```

**Comment by glauco** [comment]
@iefserge Oh, I was surprised by that!
Thank you for bringing this up and letting me know about this issue! :)

I've submitted another commit, that might solve the problem:

``` sh
node v6.0.0
const (this branch)

eshttp git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 880ms (0.0088ms per connection)
```

Removing all `let` occurrences, but keeping `const` occurrences, do not affect performance that much.

Would it still be fine doing so wherever it is possible, but avoiding `let` until V8 developers optimize it?

**Comment by iefserge** [comment]
@glauco nice, but looks like it's still slower than `var`. Can you confirm by comparing benchmark results on the same machine?

**Comment by glauco** [comment]
Ten executions of benchmark for this pull request:

`Using node v6.1.0 (npm v3.8.6)`

``` sh
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 934ms (0.0093ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 947ms (0.0095ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 921ms (0.0092ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 891ms (0.0089ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 913ms (0.0091ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 903ms (0.0090ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 890ms (0.0089ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 883ms (0.0088ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 873ms (0.0087ms per connection)
eshttp git:master ❯ node benchmark/server-benchmark.js                                                                                                                                                                                      
started...
done 100000 connections in 882ms (0.0088ms per connection)
```

`Min: 873ms`
`Max: 947ms`
`Average: 903.7ms`

Ten executions of benchmark for the original code:

`Using node v6.1.0 (npm v3.8.6)`

``` sh
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 920ms (0.0092ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 869ms (0.0087ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 847ms (0.0085ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 851ms (0.0085ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 841ms (0.0084ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 851ms (0.0085ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 843ms (0.0084ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 832ms (0.0083ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 877ms (0.0088ms per connection)
eshttp-original git:master ❯ node benchmark/server-benchmark.js
started...
done 100000 connections in 842ms (0.0084ms per connection)
```

`Min: 832ms`
`Max: 920ms`
`Average: 857.3`

You are right when you say that the code is still slower, in that particular case, it is around `46ms` slower, on average, than the original one. I still see value in using `const` instead of var at the cost of `46ms` on average.

I also understand the drawbacks of choosing it over performance. At the end is not an easier choice to make.

Anyways, I learned quite a lot with this whole conversation.
Thank you for your inputs on it! :)

**Comment by iefserge** [comment]
@glauco Thanks for the benchmarks, looks like regression is around 5%.
Switching to `const` but not `let` feels pretty inconsistent to me, I think option here is to either keep `var`s or use Babel to compile es6 -> es5. At least until V8 is fixed.

**Comment by kesla** [comment]
@iefserge have you run these benchmarks on a later version of V8? I think that V8 has worked on getting it faster

**Pull request closed without merging**
